#ifndef GAMELOOPCONSTANTS_H_
#define GAMELOOPCONSTANTS_H_

#define WINDOW_POS_X 150
#define WINDOW_POS_Y 150

#define VIEW_WIDTH 850.0f
#define VIEW_HEIGHT 300.0f

#define DESIRED_STATE_UPDATES_PER_SECOND 60
#define DESIRED_STATE_UPDATE_DURATION_MS 16.666 // obtained as: 1000/DESIRED_STATE_UPDATES_PER_SECOND

#endif /* GAMELOOPCONSTANTS_H_ */